build_image:
  image: docker:git
  services:
  - docker:dind
  script:
  - docker login -u philipz -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t restry.gitlab.com/philipz/rpi-tensorflow .
  - docker run -ti -v $(pwd)/test:/test --rm registry.gitlab.com/philipz/rpi-tensorflow python /test/tensorflow_test1.py
  - docker push registry.gitlab.com/philipz/rpi-tensorflow
  only:
  - master
